name: Publish Packages
on:
  release:
    types: [published]

jobs:
  release_npm:
    runs-on: ubuntu-latest
    name: Publish Package to NPM
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup Node
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '16'
      - name: Patch NPM
        run: |
          npm install -g npm@8
          npm -v
      - name: Install Packages
        run: |
          npm ci
          npx lerna bootstrap --ci
      - name: Build Package
        run: npm run build
      - name: Prepare Package
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
      - name: Upload Package
        run: npx lerna publish from-git --yes
  release_github:
    runs-on: ubuntu-latest
    name: Publish Package to GITHUB
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup Node
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '16'
      - name: Patch NPM
        run: |
          npm install -g npm@8
          npm -v
      - name: Install Packages
        run: |
          npm ci
          npx lerna bootstrap --ci
      - name: Build Package
        run: npm run build
      - name: Prepare Package
        run: |
          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Package
        run: npx lerna publish from-git --registry https://npm.pkg.github.com/liesmich --yes
