name: Staged release merged
on:
    pull_request:
        types:
            - closed
        branches:
            - 'main'
concurrency:
    group: publish_release
jobs:
    create-release:
        name: Create Reelase for merged branch ${{ github.event.pull_request.head.ref }}
        if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'release-staging'
        runs-on: ubuntu-latest
        outputs:
            release_version: ${{ steps.tag_version.outputs.new_tag }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3.0.0
              with:
                  fetch-depth: 0
                  token: ${{ secrets.GITHUB_TOKEN }}
                  ref: ${{ github.event.pull_request.base.ref }}
            - name: Setup Node
              uses: actions/setup-node@v3.1.0
              with:
                  node-version: 16
                  registry-url: 'https://registry.npmjs.org'
            - name: Create Release Body
              id: get-pr-body
              run: |
                  node ./.github/extract-version.js
            - name: Bump version and push tag
              id: tag_version
              uses: mathieudutour/github-tag-action@v6.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  custom_tag: v${{ steps.get-pr-body.outputs.version }}
            - name: Create a GitHub release
              uses: ncipollo/release-action@v1.10.0
              with:
                  tag: ${{ steps.tag_version.outputs.new_tag }}
                  name: Release ${{ steps.tag_version.outputs.new_tag }}
                  body: ${{ steps.tag_version.outputs.changelog }}
    release_npm:
        runs-on: ubuntu-latest
        name: Publish Package to NPM
        needs: create-release
        timeout-minutes: 30
        steps:
            - name: Checkout
              uses: actions/checkout@v3.0.0
              with:
                  fetch-depth: 0
                  ref: ${{ needs.create-release.outputs.release_version }}
            - name: Setup Node
              uses: actions/setup-node@v3.1.0
              with:
                  node-version: 16
                  registry-url: 'https://registry.npmjs.org'
            - name: Install Packages
              run: |
                  npm ci
                  npx lerna bootstrap --ci
            - name: Build Package
              run: npm run build
            - name: Prepare Package
              run: |
                  npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
            - name: Publish Packages
              run: npx lerna publish from-git -y --no-verify-access
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    release_github:
        runs-on: ubuntu-latest
        needs: create-release
        name: Publish Package to GITHUB
        steps:
            - name: Checkout
              uses: actions/checkout@v3.0.0
              with:
                  fetch-depth: 0
                  ref: ${{ needs.create-release.outputs.release_version }}
            - name: Setup Node
              uses: actions/setup-node@v3.1.0
              with:
                  node-version: 16
            - name: Install Packages
              run: |
                  npm ci
                  npx lerna bootstrap --ci
            - name: Build Package
              run: npm run build
            - name: Prepare Package
              run: |
                  npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
            - name: Publish Packages
              run: npx lerna publish from-package -y --no-verify-access --registry https://npm.pkg.github.com/donmahallem
